# Menus
bindd = SUPER, A, Launch apps, exec, dots-rofi-launch
bindd = SUPER CTRL, C, Capture menu, exec, dots-screenshot
bindd = SUPER, ESCAPE, System menu, exec, uwsm-app -- wlogout

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, dots-toggle-waybar
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, dots-toggle-idle

# Captures
bindd = , PRINT, Screenshot, exec, dots-screenshot
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send "    $(date +"%A %H:%M  —  %d %B W%V %Y")"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, dots-exec-tui wiremix
bindd = SUPER CTRL, B, Bluetooth controls, exec, dots-exec-tui bluetui 
bindd = SUPER CTRL, W, Wifi controls, exec, dots-exec-tui impala
bindd = SUPER CTRL, T, Activity, exec, dots-exec-tui btop

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, pidof hyperlock || hyprlock & 
