# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec
bindd = SUPER SHIFT, B, Browser, exec, uwsm-app -- $BROWSER 
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, N, Editor, exec, uwsm-app -- xdg-terminal-exec -e $EDITOR

# Menus
bindd = SUPER, A, Launch apps, exec, uwsm-app -- rofi -show drun
bindd = SUPER, ESCAPE, System menu, exec, wlogout 

# Aesthetics
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle 

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Captures
# TODO: replace with flameshot?
bindd = , PRINT, Screenshot, exec, grim -g "$(slurp)"

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send -u low "    $(date +"%A %H:%M  ·  %d %B %Y  ·  Week %V")"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, dots-hypr-exec-float "uwsm-app -- xdg-terminal-exec -e wiremix"
bindd = SUPER CTRL, B, Bluetooth controls, exec, dots-hypr-exec-float "uwsm-app -- xdg-terminal-exec -e bluetui"
bindd = SUPER CTRL, W, Wifi controls, exec, dots-hypr-exec-float "uwsm-app -- xdg-terminal-exec -e impala"
bindd = SUPER CTRL, T, Activity, exec, dots-hypr-exec-float "uwsm-app -- xdg-terminal-exec -e btop"

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

