# no_anim isn't necessary but animations with these rules might look bad. use at your own discretion.
windowrule = match:class flameshot, no_anim
windowrule = match:class flameshot, float
windowrule = match:class flameshot, move 0 0
windowrule = match:class flameshot, pin
windowrule = match:class flameshot, no_initial_focus
# set this to your leftmost monitor id, otherwise you have to move your cursor to the leftmost monitor
# before executing flameshot
windowrule = match:class flameshot, monitor 1

# ctrl-c to copy from the flameshot gui gives warped images sometimes, but
# setting the env fixes it
bind = ..., exec, XDG_CURRENT_DESKTOP=sway flameshot gui
