# Prevent Telegram from stealing focus on new messages
windowrule = focus_on_activate off, match:class org.telegram.desktop

windowrule = tag -default-opacity, match:class org.telegram.desktop
windowrule = opacity 0.85 0.8, match:class org.telegram.desktop
