- name: Script to setup my configuration on Archlabs + Bspwm
  hosts: 127.0.0.1
  connection: local

  vars_prompt:
    - name: wallpaper_filename
      prompt: "Enter the filename of the wallpaper image"
      private: no

    - name: background_color
      prompt: "Enter the background color"
      private: no
