- name: Script to setup my configuration on Archlabs + Bspwm
  hosts: 127.0.0.1
  connection: local

  vars_prompt:
    - name: wallpaper_path
      prompt: "Enter absolute path to wallpaper image"
      private: no

    - name: background_color
      prompt: "Enter background color"
      private: no

  vars:
    - dotfiles_repo: https://github.com/innng/dotfiles.git 
    - tmp_folder: /tmp/

  tasks:
    - name: Get username
      shell: echo "$USER"
      register: username

    - name: Install pip
      shell: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py

    - name: Clone yay
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: "{{ tmp_folder }}yay/"

    - name: Install yay
      shell: makepkg -si --noconfirm
      args:
        chdir: "{{ tmp_folder }}yay/"

    - name: Install zsh
      shell: yay -S zsh --noconfirm
      
    - stat:
        path: "/home/{{ username.stdout }}/.oh-my-zsh/"
      register: zsh_exists

    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        chdir: "/home/{{ username.stdout }}/"
      when: not zsh_exists.stat.exists

    - name: Install pywal
      pip:
        name: pywal
      become: True

    - name: Set pywal
      shell: "wal -i \"{{ wallpaper_path }}\" -b \"{{ background_color }}\""

    - name: Install polybar
      shell: yay -S polybar --noconfirm --needed

    - name: Clone dotfiles repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ tmp_folder }}dotfiles/"

    - name: Copy xorg configurations
      copy:
        src: "{{ tmp_folder }}/dotfiles/X11/"
        dest: "/etc/X11/xorg.conf.d/"
      become: True
      
    - name: Copy .Xresources
      copy:
        src: "{{ tmp_folder}}dotfiles/X/.Xresources"
        dest: "/home/{{ username.stdout }}/.Xresources"
        backup: yes

    - name: Change username on .Xresources
      replace:
        path: "/home/{{ username.stdout }}/.Xresources"
        regexp: 'username'
        replace: '{{ username.stdout }}'

    - name: Copy .xprofile
      copy:
        src: "{{ tmp_folder }}dotfiles/X/.xprofile"
        dest: "/home/{{ username.stdout }}/.xprofile"
        backup: yes

    - name: Copy bspwmrc
      copy:
        src: "{{ tmp_folder }}dotfiles/bspwm/"
        dest: "/home/{{ username.stdout }}/.config/bspwm/"
        backup: yes
    
    - name: Change username on bspwmrc
      replace:
        path: "/home/{{ username.stdout }}/.config/bspwm/bspwmrc"
        regexp: 'username'
        replace: '{{ username.stdout }}'

    - name: Copy sxhkdrc
      copy:
        src: "{{ tmp_folder }}dotfiles/sxhkd/"
        dest: "/home/{{ username.stdout }}/.config/sxhkd/"
        backup: yes

    - name: Copy polybar files
      copy:
        src: "{{ tmp_folder }}dotfiles/polybar/"
        dest: "/home/{{ username.stdout }}/.config/polybar/"
        backup: yes

    - name: Change username on polybar config
      replace:
        path: "/home/{{ username.stdout }}/.config/polybar/config"
        regexp: 'username'
        replace: '{{ username.stdout }}'
    
    - name: Copy rofi config
      copy:
        src: "{{ tmp_folder }}dotfiles/rofi/"
        dest: "/home/{{ username.stdout }}/.config/rofi"
        backup: yes

    - name: Change username on rofi config
      replace:
        path: "/home/{{ username.stdout }}/.config/rofi/config.rasi"
        regexp: 'username'
        replace: '{{ username.stdout }}'

    - name: Copy .vimrc
      copy:
        src: "{{ tmp_folder }}dotfiles/.vimrc"
        dest: "/home/{{ username.stdout }}/.vimrc"
        backup: yes

    - name: Install VisualStudioCode
      shell: yay -S code --noconfirm --needed

    - name: Install spotify
      shell: yay -S spotify --noconfirm --needed

    - name: Install flameshot
      shell: yay -S flameshot --noconfirm --needed

    - name: Install telegram desktop
      shell: yay -S telegram-desktop --noconfirm --needed

    - name: Install zip 
      shell: yay -S zip --noconfirm --needed

    - name: Install unzip
      shell: yay -S unzip --noconfirm --needed
     
    - name: Install python-dbus for polybar spotify status
      shell: yay -S python-dbus --noconfirm --needed
 
