# App-specific tweaks
source = ~/.dots/source/hypr/apps/browser.conf
source = ~/.dots/source/hypr/apps/hyprshot.conf
source = ~/.dots/source/hypr/apps/steam.conf
source = ~/.dots/source/hypr/apps/telegram.conf
source = ~/.dots/source/hypr/apps/terminals.conf
