# App-specific tweaks
#source = ~/.dots/source/hypr/apps/1password.conf
#source = ~/.dots/source/hypr/apps/bitwarden.conf
source = ~/.dots/source/hypr/apps/browser.conf
#source = ~/.dots/source/hypr/apps/flameshot.conf
#source = ~/.dots/source/hypr/apps/hyprshot.conf
#source = ~/.dots/source/hypr/apps/localsend.conf
#source = ~/.dots/source/hypr/apps/moonlight.conf
#source = ~/.dots/source/hypr/apps/pip.conf
#source = ~/.dots/source/hypr/apps/qemu.conf
#source = ~/.dots/source/hypr/apps/retroarch.conf
#source = ~/.dots/source/hypr/apps/steam.conf
#source = ~/.dots/source/hypr/apps/geforce.conf
source = ~/.dots/source/hypr/apps/spotify.conf
source = ~/.dots/source/hypr/apps/telegram.conf
source = ~/.dots/source/hypr/apps/terminals.conf
