exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- mako
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- awww-daemon
exec-once = uwsm-app -- swayosd-server
exec-once = sleep 3 && uwsm-app -- linux-wallpaperengine --screen-root DP-1 --scaling fill --bg 2954387038 --screen-root DP-2 --scaling fill --bg 2954387038 --no-audio-processing --fps 60 --disable-mouse --disable-parallax --fullscreen-pause-only-active
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

