source = ~/.dots/config/hypr/bindings/media.conf
source = ~/.dots/config/hypr/bindings/tiling.conf
source = ~/.dots/config/hypr/bindings/utilities.conf
source = ~/.dots/config/hypr/envs.conf
source = ~/.dots/config/hypr/input.conf
source = ~/.dots/config/hypr/looknfeel.conf
source = ~/.dots/config/hypr/windows.conf

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }

