source = ~/.dots/source/hypr/apps.conf
source = ~/.dots/source/hypr/bindings/media.conf
source = ~/.dots/source/hypr/bindings/tiling.conf
source = ~/.dots/source/hypr/bindings/utilities.conf
source = ~/.dots/source/hypr/envs.conf
source = ~/.dots/source/hypr/input.conf
source = ~/.dots/source/hypr/looknfeel.conf
source = ~/.dots/source/hypr/monitors.conf
source = ~/.dots/source/hypr/windows.conf
source = ~/.dots/source/hypr/workspaces.conf

source = ~/.config/theme/hyprland.conf
