# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant = intl
    kb_model =
    kb_options = compose:rctrl
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

misc {
    key_press_enables_dpms = true  # key press will trigger wake
    mouse_move_enables_dpms = true # mouse move will trigger wake
}
