[Setting]
prefs_path             = /home/ing/.var/app/com.spotify.Client/config/spotify/prefs 
spotify_launch_flags   = 
check_spicetify_update = 1
always_enable_devtools = 0
spotify_path           = /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/
current_theme          = 
color_scheme           = 
inject_theme_js        = 1
inject_css             = 1
replace_colors         = 1
overwrite_assets       = 0

[Preprocesses]
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1
disable_sentry     = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = 
custom_apps           = 
sidebar_config        = 0

[Patch]

; DO NOT CHANGE!
[Backup]
version = 
with    = 
