#!/bin/bash
#
# Generate Application Theme Configurations
# 
# Converts a single theme definition file into application-specific color configs
# This script sources the theme file and generates color configurations for each application
#
# Usage:
#   ./generate-theme.sh                           # Uses catppuccin-mocha.sh
#   ./generate-theme.sh catppuccin-latte.sh      # Use a different theme
#

set -e

# ============================================================
# Setup
# ============================================================

THEME_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GENERATED_DIR="$THEME_DIR/generated"

# Theme file to use (default: catppuccin-mocha.sh)
THEME_FILE="${1:-catppuccin-mocha.sh}"
THEME_PATH="$THEME_DIR/$THEME_FILE"

# Verify theme file exists
if [ ! -f "$THEME_PATH" ]; then
    echo "✗ Theme file not found: $THEME_PATH"
    exit 1
fi

# Create generated directory
mkdir -p "$GENERATED_DIR"

# Load theme variables
source "$THEME_PATH"

echo "Generating theme configs from: $THEME_FILE"

# ============================================================
# Helper Functions
# ============================================================

hex_to_hex() {
    # Remove # if present
    echo "${1#\#}"
}

hex_to_decimal() {
    # Convert hex to decimal (for Hyprland's 0xffrrggbb format)
    printf "%d" "0x${1#\#}"
}

# ============================================================
# Generate Rofi Colors
# ============================================================

generate_rofi_colors() {
    local file="$GENERATED_DIR/rofi.colors"
    
    cat > "$file" << EOF
/* Generated - DO NOT EDIT
   This file is auto-generated by generate-theme.sh
   Edit catppuccin-mocha.sh instead and re-run the generator
   
   To use: @import "path/to/rofi.colors" in your theme file
*/

* {
    /* Background colors */
    main-bg:            ${THEME_BG}e6;
    alt-bg:             ${THEME_BG_LIGHT}e6;
    
    /* Foreground colors */
    main-fg:            ${THEME_FG}ff;
    alt-fg:             ${THEME_FG_MUTED}ff;
    
    /* Accent colors */
    main-br:            ${THEME_PRIMARY}ff;
    select-bg:          ${THEME_PRIMARY}ff;
    select-fg:          ${THEME_BG_DARK}ff;
    
    /* Extra color */
    main-ex:            ${THEME_SELECT_BG}ff;
    
    /* Borders and separators */
    separatorcolor:     transparent;
    border-color:       transparent;
}
EOF
    
    echo "✓ Generated: $file"
}

# ============================================================
# Generate Dunst Colors
# ============================================================

generate_dunst_colors() {
    local file="$GENERATED_DIR/dunst.colors"
    
    cat > "$file" << EOF
# Generated - DO NOT EDIT
# This file is auto-generated by generate-theme.sh
# Edit catppuccin-mocha.sh instead and re-run the generator
#
# To use: source this file in dunst config with:
#   source = ~/.dots/extra/theme/generated/dunst.colors

[colors]
background = $THEME_BG
foreground = $THEME_FG
frame_color = $THEME_PRIMARY

[urgency_low]
background = $THEME_BG_LIGHT
foreground = $THEME_FG
frame = $THEME_PRIMARY

[urgency_normal]
background = $THEME_BG
foreground = $THEME_FG
frame = $THEME_PRIMARY

[urgency_critical]
background = $THEME_ERROR
foreground = $THEME_BG
frame = $THEME_ERROR
EOF
    
    echo "✓ Generated: $file"
}

# ============================================================
# Generate Hyprland Colors
# ============================================================

generate_hyprland_colors() {
    local file="$GENERATED_DIR/hyprland.colors"
    
    # Format colors for Hyprland (0xffRRGGBB format)
    local bg_hex="0xff$(hex_to_hex "$THEME_BG")"
    local fg_hex="0xff$(hex_to_hex "$THEME_FG")"
    local primary_hex="0xff$(hex_to_hex "$THEME_PRIMARY")"
    local secondary_hex="0xff$(hex_to_hex "$THEME_SECONDARY")"
    local accent_hex="0xff$(hex_to_hex "$THEME_ACCENT")"
    local error_hex="0xff$(hex_to_hex "$THEME_ERROR")"
    
    cat > "$file" << EOF
# Generated - DO NOT EDIT
# This file is auto-generated by generate-theme.sh
# Edit catppuccin-mocha.sh instead and re-run the generator
#
# To use: source = ~/.dots/extra/theme/generated/hyprland.colors

# Theme colors for Hyprland
\$bg = $bg_hex
\$fg = $fg_hex
\$primary = $primary_hex
\$secondary = $secondary_hex
\$accent = $accent_hex
\$error = $error_hex

# Background variants
\$bg_dark = 0xff$(hex_to_hex "$THEME_BG_DARK")
\$bg_light = 0xff$(hex_to_hex "$THEME_BG_LIGHT")
\$bg_medium = 0xff$(hex_to_hex "$THEME_BG_MEDIUM")

# Text colors
\$text_light = 0xff$(hex_to_hex "$THEME_FG_LIGHT")
\$text_muted = 0xff$(hex_to_hex "$THEME_FG_MUTED")

# UI Elements
\$border = $primary_hex
\$error = $error_hex
\$success = 0xff$(hex_to_hex "$THEME_SUCCESS")
\$warning = 0xff$(hex_to_hex "$THEME_WARNING")
EOF
    
    echo "✓ Generated: $file"
}

# ============================================================
# Generate Kitty Colors
# ============================================================

generate_kitty_colors() {
    local file="$GENERATED_DIR/kitty.colors"
    
    cat > "$file" << EOF
# Generated - DO NOT EDIT
# This file is auto-generated by generate-theme.sh
# Edit catppuccin-mocha.sh instead and re-run the generator
#
# To use: include this file in ~/.config/kitty/kitty.conf with:
#   include ~/.dots/extra/theme/generated/kitty.colors

# Basic colors
foreground              $THEME_FG
background              $THEME_BG
selection_foreground    $THEME_SELECT_FG
selection_background    $THEME_SELECT_BG

# Cursor
cursor                  #f5e0dc
cursor_text_color       $THEME_BG

# ANSI Colors (0-7)
color0                  $THEME_COLOR0
color1                  $THEME_COLOR1
color2                  $THEME_COLOR2
color3                  $THEME_COLOR3
color4                  $THEME_COLOR4
color5                  $THEME_COLOR5
color6                  $THEME_COLOR6
color7                  $THEME_COLOR7

# ANSI Bright Colors (8-15)
color8                  $THEME_COLOR8
color9                  $THEME_COLOR9
color10                 $THEME_COLOR10
color11                 $THEME_COLOR11
color12                 $THEME_COLOR12
color13                 $THEME_COLOR13
color14                 $THEME_COLOR14
color15                 $THEME_COLOR15
EOF
    
    echo "✓ Generated: $file"
}

# ============================================================
# Main
# ============================================================

main() {
    echo ""
    echo "════════════════════════════════════════════════════"
    echo "Generating Application Theme Configurations"
    echo "════════════════════════════════════════════════════"
    echo ""
    
    generate_rofi_colors
    generate_dunst_colors
    generate_hyprland_colors
    generate_kitty_colors
    
    echo ""
    echo "════════════════════════════════════════════════════"
    echo "✓ Theme generation complete!"
    echo "════════════════════════════════════════════════════"
    echo ""
    echo "Generated files in: $GENERATED_DIR"
    echo ""
    echo "Next steps:"
    echo "  1. Verify generated colors match your applications"
    echo "  2. Update application configs to source generated colors"
    echo "  3. Restart applications to apply new colors"
    echo ""
}

main "$@"
