#!/bin/bash

if omarchy-cmd-present voxtype; then
  voxtype status --follow --extended --format json | while read -r line; do
    echo "$line" | jq -c '. + {alt: .class}'
  done
else
  echo '{"alt": "", "tooltip": ""}'
fi
