#!/bin/bash

# Creates a new Omarchy migration named after the unix timestamp of the last commit.
# Only intended for Omarchy developers.

cd ~/.local/share/omarchy
migration_file="$HOME/.local/share/omarchy/migrations/$(git log -1 --format=%cd --date=unix).sh"
touch $migration_file

if [[ $1 != "--no-edit" ]]; then
  nvim $migration_file
fi

echo $migration_file
