#!/bin/bash

# Returns a list of all the monospace fonts available on the system that can be set using omarchy-font-set.

fc-list :spacing=100 -f "%{family[0]}\n" | grep -v -i -E 'emoji|signwriting|omarchy' | sort -u
