#!/bin/bash
set -e

# Attempt to reinstall all default Omarchy packages and reset all the default configs.

echo -e "This will reinstall all the default Omarchy packages and reset all default configs.\nWarning: All user changes to configs will be lost.\n"

if gum confirm "Are you sure you want to reinstall and lose all config changes?"; then
  omarchy-reinstall-git
  omarchy-reinstall-pkgs
  omarchy-reinstall-configs

  gum confirm "System has been reinstalled. Reboot?" && omarchy-system-reboot
fi
