#!/bin/bash

set -e

# Ensure screensaver/sleep doesn't set in during updates
hyprctl dispatch tagwindow +noidle &> /dev/null || true

# Capture update logs
exec > >(tee "/tmp/omarchy-update.log") 2>&1

# Perform all update steps
omarchy-update-time
omarchy-update-keyring
omarchy-update-available-reset
omarchy-update-system-pkgs
omarchy-migrate
omarchy-update-aur-pkgs
omarchy-update-orphan-pkgs
omarchy-hook post-update

omarchy-update-analyze-logs

omarchy-update-restart

# Re-enable screensaver/sleep after updates
hyprctl dispatch tagwindow -- -noidle &> /dev/null || true
