#!/bin/bash

if [[ ! -d /usr/lib/modules/$(uname -r) ]]; then
  gum confirm "Linux kernel has been updated. Reboot?" && omarchy-system-reboot
elif [[ -f $HOME/.local/state/omarchy/reboot-required ]]; then
  gum confirm "Updates require reboot. Ready?" && omarchy-system-reboot
fi

for file in "$HOME"/.local/state/omarchy/restart-*-required; do
  if [[ -f $file ]]; then
    filename=$(basename "$file")
    service=$(echo "$filename" | sed 's/restart-\(.*\)-required/\1/')
    echo "Restarting $service"
    omarchy-state clear "$filename"
    omarchy-restart-"$service"
  fi
done
