#!/bin/bash

# Run a named hook, like post-update (available in ~/.config/omarchy/hooks/post-update).

set -e

if (( $# < 1 )); then
  echo "Usage: omarchy-hook [name] [args...]"
  exit 1
fi

HOOK=$1
HOOK_PATH="$HOME/.config/omarchy/hooks/$1"
shift

if [[ -f $HOOK_PATH ]]; then
  bash "$HOOK_PATH" "$@"
fi
