#!/bin/bash

STATE_FILE=~/.local/state/omarchy/toggles/screensaver-off

if [[ -f $STATE_FILE ]]; then
  rm -f $STATE_FILE
  notify-send "󱄄   Screensaver enabled"
else
  mkdir -p "$(dirname $STATE_FILE)"
  touch $STATE_FILE
  notify-send "󱄄   Screensaver disabled"
fi
