#!/bin/bash

if [[ -f ~/.config/alacritty/alacritty.toml ]]; then
  touch ~/.config/alacritty/alacritty.toml
fi

if pgrep -x kitty >/dev/null; then
  killall -SIGUSR1 kitty >/dev/null
fi

if pgrep -x ghostty >/dev/null; then
  killall -SIGUSR2 ghostty
fi
