#!/bin/bash

STATE_FILE=~/.local/state/omarchy/toggles/suspend-off

if [[ -f $STATE_FILE ]]; then
  rm -f $STATE_FILE
  notify-send "󰒲   Suspend now available in system menu"
else
  mkdir -p "$(dirname $STATE_FILE)"
  touch $STATE_FILE
  notify-send "󰒲   Suspend removed from system menu"
fi
