#!/bin/bash

# Install the Tailscale mesh VPN service and a web app for the Tailscale Admin Console.

curl -fsSL https://tailscale.com/install.sh | sh

echo -e "\nStarting Tailscale..."
sudo tailscale up --accept-routes

omarchy-webapp-install "Tailscale" "https://login.tailscale.com/admin/machines" https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/tailscale-light.png
