#!/bin/bash

# Install and launch Steam after first letting the user pick the correct grahics card drivers.

set -e

echo "Now pick dependencies matching your graphics card"
sudo pacman -S steam
setsid gtk-launch steam >/dev/null 2>&1 &
